sudo: required
dist: trusty

matrix:
  include:
  - language: java
    jdk: oraclejdk8
    env: BUILD=MVN

  - language: java
    jdk: oraclejdk8
    env: BUILD=GRADLE

install:
  - case "$BUILD" in
      "MVN")
        mkdir protoc ;
        cd protoc ;
        curl -L -o protoc.zip https://github.com/google/protobuf/releases/download/v3.0.2/protoc-3.0.2-linux-x86_64.zip ;
        unzip protoc.zip ;
        export PATH=`pwd`/bin/:$PATH ;
        protoc --version ;
        cd .. ;;
    esac

script:
  - case "$BUILD" in
      "MVN")
        mvn verify ;;
      "GRADLE")
        ./gradlew clean assemble --stacktrace ;
        ./gradlew check --stacktrace ;;
      *)
        echo "Missing case $BUILD" ;
        exit 1 ;;
    esac

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
